# Generated by Django 4.1.3 on 2022-11-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Varição', 'verbose_name_plural': 'Varições'},
        ),
    ]
